# Generated by Django 3.1 on 2020-08-14 23:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('restaurants', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant_match_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediate.restaurantmatch'),
        ),
    ]
